# nginx/nginx.conf - generando push para generar imagen
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Configuración para Angular SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para todos los archivos estáticos
    location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

    # Health check
    location /health {
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}